### ISSUE TITLE
I can't get cf_clearance cookie from phind

### ISSUE THREAD

**Issue by tomfortheking** [mishalhossin/Coding-Chatbot-Gpt4Free#1]
I would like to ask if I can still get cf_clearance from phind now
![20230429175015](https://user-images.githubusercontent.com/71697442/235296741-2503d6cf-315c-42e0-b56b-9fa5112773e8.png)

**Comment by mishalhossin** [comment]
> I would like to ask if I can still get cf_clearance from phind now ![20230429175015](https://user-images.githubusercontent.com/71697442/235296741-2503d6cf-315c-42e0-b56b-9fa5112773e8.png)

delete all cookie then reload and try again

**Comment by mishalhossin** [comment]
or just use mine ```
oX1yLxDwrowoSuEC.8nAAkNGDiXJyZf80ctIAZrspVc-1682695201-0-160
```

**Comment by mishalhossin** [comment]
Or chat on phind until you get Cloudflare captcha

**Comment by mishalhossin** [comment]
Still wanna use it for free ? [Gpt4free](https://chat.chatbot.sex/chat/)

**Comment by tomfortheking** [comment]
Thank you very much, but the method of deleting cookies didn't work and I didn't get Cloudflare captcha. If you can get cf_clearance cookies from Phind normally, it seems to be my own problem.

**Comment by mishalhossin** [comment]
> Thank you very much, but the method of deleting cookies didn't work and I didn't get Cloudflare captcha. If you can get cf_clearance cookies from Phind normally, it seems to be my own problem.

Hey try a different browser like chrome or brave that supports chromium extension


or use this extension to change useragent then get your new agent from google and clear cookie then it should work
https://chrome.google.com/webstore/detail/user-agent-switcher-for-c/djflhoibgkdhkhhcedjiklpkjnoahfmg

**Comment by mishalhossin** [comment]
If that still dosent work use a vpn and a diffrent chromium browser then it will work...you shouldnt have to do this

**Comment by mishalhossin** [comment]
If you need more help dm me at discord [Mishal#1916](https://discord.com/users/1025245410224263258)

**Comment by mishalhossin** [comment]
You can invite it to your server and dm it https://discord.com/api/oauth2/authorize?client_id=1099712961733472327&permissions=8&scope=applications.commands%20bot

**Comment by tomfortheking** [comment]
Thanks for your help, I think my problem may be related to VPN, I have been opening the VPN access website, let me try a different device.

**Comment by bolavefasfas** [comment]
![image](https://user-images.githubusercontent.com/82230241/235438280-8f524178-251b-4a01-a0d8-9b785b9c799e.png)

I am also unable to get cf_clearance cookie

 Tried all ueragent chaning via the extenstion 
 
 tried firefox brave edge 🙁
 
 Nothing works

**Comment by TotoB12** [comment]
Use this one:
[https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg](https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg)
